import BasicLayout from "@/components/layout/BasicLayout"
import Modal from "@/components/modal/Modal"
import RecoilProvider from "@/utils/lib/RecoilProvider"
import StyledComponentsRegistry from "@/utils/lib/StyledComponentsRegistry"
import { GlobalStyle } from "@/utils/style/globalStyle"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="ko">
            <body className={inter.className}>
                <RecoilProvider>
                    <StyledComponentsRegistry>
                        <GlobalStyle />
                        <BasicLayout>{children}</BasicLayout>
                        <Modal />
                    </StyledComponentsRegistry>
                </RecoilProvider>
            </body>
        </html>
    )
}
