import type { Metadata } from "next";
import AppLayout from "@/components/layout/AppLayout";
import StyledComponentsRegistry from "@/utils/lib/StyledComponentsRegistry";
import { GlobalStyle } from "@/utils/style/globalStyle";
import { pretendard } from "@/utils/style/fonts";

export const metadata: Metadata = {
    title: "Ya-Pass",
    description: "Generated by create next app",
    icons: {
        icon: "/images/favicon/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={pretendard.className}>
                <StyledComponentsRegistry>
                    <GlobalStyle />
                    <AppLayout>{children}</AppLayout>
                    <div id="modal"></div>
                    <div id="toast"></div>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
