export const SeatData2 = [
    {
        id: "1",
        theaterCode: "00000001",
        name: "서울 상상나라극장",
        location: "서울시 광진구 능동로216, 서울상상나라 지하 1층",
        size: "소극장",
        seats: [
            {
                id: "1",
                rowName: "가",
                name: "1",
                isDisabled: false,
                state: 1,
            },
            {
                id: "2",
                rowName: "가",
                name: "2",
                isDisabled: false,
                state: 1,
            },
            {
                id: "3",
                rowName: "가",
                name: "3",
                isDisabled: false,
                state: 1,
            },
            {
                id: "4",
                rowName: "가",
                name: "4",
                isDisabled: false,
                state: 1,
            },
            {
                id: "5",
                rowName: "가",
                name: "5",
                isDisabled: false,
                state: 1,
            },
            {
                id: "6",
                rowName: "가",
                name: "6",
                isDisabled: false,
                state: 1,
            },
            {
                id: "7",
                rowName: "가",
                name: "7",
                isDisabled: false,
                state: 1,
            },
            {
                id: "8",
                rowName: "가",
                name: "8",
                isDisabled: false,
                state: 1,
            },
            {
                id: "9",
                rowName: "가",
                name: "9",
                isDisabled: false,
                state: 1,
            },
            {
                id: "10",
                rowName: "가",
                name: "10",
                isDisabled: false,
                state: 1,
            },
            {
                id: "11",
                rowName: "가",
                name: "11",
                isDisabled: false,
                state: 1,
            },
            {
                id: "12",
                rowName: "가",
                name: "12",
                isDisabled: false,
                state: 1,
            },
            {
                id: "13",
                rowName: "가",
                name: "13",
                isDisabled: false,
                state: 1,
            },
            {
                id: "14",
                rowName: "가",
                name: "14",
                isDisabled: false,
                state: 1,
            },
            {
                id: "15",
                rowName: "가",
                name: "15",
                isDisabled: false,
                state: 1,
            },
            {
                id: "16",
                rowName: "가",
                name: "16",
                isDisabled: false,
                state: 1,
            },
            {
                id: "17",
                rowName: "가",
                name: "17",
                isDisabled: false,
                state: 1,
            },
            {
                id: "18",
                rowName: "가",
                name: "18",
                isDisabled: false,
                state: 1,
            },
            {
                id: "19",
                rowName: "가",
                name: "19",
                isDisabled: false,
                state: 1,
            },
            {
                id: "20",
                rowName: "가",
                name: "20",
                isDisabled: false,
                state: 1,
            },
            {
                id: "21",
                rowName: "가",
                name: "21",
                isDisabled: false,
                state: 1,
            },
            {
                id: "22",
                rowName: "가",
                name: "22",
                isDisabled: false,
                state: 1,
            },
            {
                id: "23",
                rowName: "가",
                name: "23",
                isDisabled: false,
                state: 1,
            },
            {
                id: "24",
                rowName: "가",
                name: "24",
                isDisabled: false,
                state: 1,
            },
            {
                id: "25",
                rowName: "가",
                name: "25",
                isDisabled: false,
                state: 1,
            },
            {
                id: "26",
                rowName: "가",
                name: "26",
                isDisabled: false,
                state: 1,
            },
            {
                id: "27",
                rowName: "가",
                name: "27",
                isDisabled: false,
                state: 1,
            },
            {
                id: "28",
                rowName: "가",
                name: "28",
                isDisabled: false,
                state: 1,
            },
            {
                id: "29",
                rowName: "나",
                name: "1",
                isDisabled: false,
                state: 1,
            },
            {
                id: "30",
                rowName: "나",
                name: "2",
                isDisabled: false,
                state: 1,
            },
            {
                id: "31",
                rowName: "나",
                name: "3",
                isDisabled: false,
                state: 1,
            },
            {
                id: "32",
                rowName: "나",
                name: "4",
                isDisabled: false,
                state: 1,
            },
            {
                id: "33",
                rowName: "나",
                name: "5",
                isDisabled: false,
                state: 1,
            },
            {
                id: "34",
                rowName: "나",
                name: "6",
                isDisabled: false,
                state: 1,
            },
            {
                id: "35",
                rowName: "나",
                name: "7",
                isDisabled: false,
                state: 1,
            },
            {
                id: "36",
                rowName: "나",
                name: "8",
                isDisabled: false,
                state: 1,
            },
            {
                id: "37",
                rowName: "나",
                name: "9",
                isDisabled: false,
                state: 1,
            },
            {
                id: "38",
                rowName: "나",
                name: "10",
                isDisabled: false,
                state: 1,
            },
            {
                id: "39",
                rowName: "나",
                name: "11",
                isDisabled: false,
                state: 1,
            },
            {
                id: "40",
                rowName: "나",
                name: "12",
                isDisabled: false,
                state: 1,
            },
            {
                id: "41",
                rowName: "나",
                name: "13",
                isDisabled: false,
                state: 1,
            },
            {
                id: "42",
                rowName: "나",
                name: "14",
                isDisabled: false,
                state: 1,
            },
            {
                id: "43",
                rowName: "나",
                name: "15",
                isDisabled: false,
                state: 1,
            },
            {
                id: "44",
                rowName: "나",
                name: "16",
                isDisabled: false,
                state: 1,
            },
            {
                id: "45",
                rowName: "나",
                name: "17",
                isDisabled: false,
                state: 1,
            },
            {
                id: "46",
                rowName: "나",
                name: "18",
                isDisabled: false,
                state: 1,
            },
            {
                id: "47",
                rowName: "나",
                name: "19",
                isDisabled: false,
                state: 1,
            },
            {
                id: "48",
                rowName: "나",
                name: "20",
                isDisabled: false,
                state: 1,
            },
            {
                id: "49",
                rowName: "나",
                name: "21",
                isDisabled: false,
                state: 1,
            },
            {
                id: "50",
                rowName: "나",
                name: "22",
                isDisabled: false,
                state: 1,
            },
            {
                id: "51",
                rowName: "나",
                name: "23",
                isDisabled: false,
                state: 1,
            },
            {
                id: "52",
                rowName: "나",
                name: "24",
                isDisabled: false,
                state: 1,
            },
            {
                id: "53",
                rowName: "나",
                name: "25",
                isDisabled: false,
                state: 1,
            },
            {
                id: "54",
                rowName: "나",
                name: "26",
                isDisabled: false,
                state: 1,
            },
            {
                id: "55",
                rowName: "나",
                name: "27",
                isDisabled: false,
                state: 1,
            },
            {
                id: "56",
                rowName: "나",
                name: "28",
                isDisabled: false,
                state: 1,
            },
            {
                id: "57",
                rowName: "다",
                name: "1",
                isDisabled: false,
                state: 1,
            },
            {
                id: "58",
                rowName: "다",
                name: "2",
                isDisabled: false,
                state: 1,
            },
            {
                id: "59",
                rowName: "다",
                name: "3",
                isDisabled: false,
                state: 1,
            },
            {
                id: "60",
                rowName: "다",
                name: "4",
                isDisabled: false,
                state: 1,
            },
            {
                id: "61",
                rowName: "다",
                name: "5",
                isDisabled: false,
                state: 1,
            },
            {
                id: "62",
                rowName: "다",
                name: "6",
                isDisabled: false,
                state: 1,
            },
            {
                id: "63",
                rowName: "다",
                name: "7",
                isDisabled: false,
                state: 1,
            },
            {
                id: "64",
                rowName: "다",
                name: "8",
                isDisabled: false,
                state: 1,
            },
            {
                id: "65",
                rowName: "다",
                name: "9",
                isDisabled: false,
                state: 1,
            },
            {
                id: "66",
                rowName: "다",
                name: "10",
                isDisabled: false,
                state: 1,
            },
            {
                id: "67",
                rowName: "다",
                name: "11",
                isDisabled: false,
                state: 1,
            },
            {
                id: "68",
                rowName: "다",
                name: "12",
                isDisabled: false,
                state: 1,
            },
            {
                id: "69",
                rowName: "다",
                name: "13",
                isDisabled: false,
                state: 1,
            },
            {
                id: "70",
                rowName: "다",
                name: "14",
                isDisabled: false,
                state: 1,
            },
            {
                id: "71",
                rowName: "다",
                name: "15",
                isDisabled: false,
                state: 1,
            },
            {
                id: "72",
                rowName: "다",
                name: "16",
                isDisabled: false,
                state: 1,
            },
            {
                id: "73",
                rowName: "다",
                name: "17",
                isDisabled: false,
                state: 1,
            },
            {
                id: "74",
                rowName: "다",
                name: "18",
                isDisabled: false,
                state: 1,
            },
            {
                id: "75",
                rowName: "다",
                name: "19",
                isDisabled: false,
                state: 1,
            },
            {
                id: "76",
                rowName: "다",
                name: "20",
                isDisabled: false,
                state: 1,
            },
            {
                id: "77",
                rowName: "다",
                name: "21",
                isDisabled: false,
                state: 1,
            },
            {
                id: "78",
                rowName: "다",
                name: "22",
                isDisabled: false,
                state: 1,
            },
            {
                id: "79",
                rowName: "다",
                name: "23",
                isDisabled: false,
                state: 1,
            },
            {
                id: "80",
                rowName: "다",
                name: "24",
                isDisabled: false,
                state: 1,
            },
            {
                id: "81",
                rowName: "다",
                name: "25",
                isDisabled: false,
                state: 1,
            },
            {
                id: "82",
                rowName: "다",
                name: "26",
                isDisabled: false,
                state: 1,
            },
            {
                id: "83",
                rowName: "다",
                name: "27",
                isDisabled: false,
                state: 1,
            },
            {
                id: "84",
                rowName: "다",
                name: "28",
                isDisabled: false,
                state: 1,
            },
            {
                id: "85",
                rowName: "라",
                name: "1",
                isDisabled: false,
                state: 1,
            },
            {
                id: "86",
                rowName: "라",
                name: "2",
                isDisabled: false,
                state: 1,
            },
            {
                id: "87",
                rowName: "라",
                name: "3",
                isDisabled: false,
                state: 1,
            },
            {
                id: "88",
                rowName: "라",
                name: "4",
                isDisabled: false,
                state: 1,
            },
            {
                id: "89",
                rowName: "라",
                name: "5",
                isDisabled: false,
                state: 1,
            },
            {
                id: "90",
                rowName: "라",
                name: "6",
                isDisabled: false,
                state: 1,
            },
            {
                id: "91",
                rowName: "라",
                name: "7",
                isDisabled: false,
                state: 1,
            },
            {
                id: "92",
                rowName: "라",
                name: "8",
                isDisabled: false,
                state: 1,
            },
            {
                id: "93",
                rowName: "라",
                name: "9",
                isDisabled: false,
                state: 1,
            },
            {
                id: "94",
                rowName: "라",
                name: "10",
                isDisabled: false,
                state: 1,
            },
            {
                id: "95",
                rowName: "라",
                name: "11",
                isDisabled: false,
                state: 1,
            },
            {
                id: "96",
                rowName: "라",
                name: "12",
                isDisabled: false,
                state: 1,
            },
            {
                id: "97",
                rowName: "라",
                name: "13",
                isDisabled: false,
                state: 1,
            },
            {
                id: "98",
                rowName: "라",
                name: "14",
                isDisabled: false,
                state: 1,
            },
            {
                id: "99",
                rowName: "라",
                name: "15",
                isDisabled: false,
                state: 1,
            },
            {
                id: "100",
                rowName: "라",
                name: "16",
                isDisabled: false,
                state: 1,
            },
            {
                id: "101",
                rowName: "라",
                name: "17",
                isDisabled: false,
                state: 1,
            },
            {
                id: "102",
                rowName: "라",
                name: "18",
                isDisabled: false,
                state: 1,
            },
            {
                id: "103",
                rowName: "라",
                name: "19",
                isDisabled: false,
                state: 1,
            },
            {
                id: "104",
                rowName: "라",
                name: "20",
                isDisabled: false,
                state: 1,
            },
            {
                id: "105",
                rowName: "라",
                name: "21",
                isDisabled: false,
                state: 1,
            },
            {
                id: "106",
                rowName: "라",
                name: "22",
                isDisabled: false,
                state: 1,
            },
            {
                id: "107",
                rowName: "라",
                name: "23",
                isDisabled: false,
                state: 1,
            },
            {
                id: "108",
                rowName: "라",
                name: "24",
                isDisabled: false,
                state: 1,
            },
            {
                id: "109",
                rowName: "라",
                name: "25",
                isDisabled: false,
                state: 1,
            },
            {
                id: "110",
                rowName: "라",
                name: "26",
                isDisabled: false,
                state: 1,
            },
            {
                id: "111",
                rowName: "라",
                name: "27",
                isDisabled: false,
                state: 1,
            },
            {
                id: "112",
                rowName: "라",
                name: "28",
                isDisabled: false,
                state: 1,
            },
            {
                id: "113",
                rowName: "마",
                name: "1",
                isDisabled: false,
                state: 1,
            },
            {
                id: "114",
                rowName: "마",
                name: "2",
                isDisabled: false,
                state: 1,
            },
            {
                id: "115",
                rowName: "마",
                name: "3",
                isDisabled: false,
                state: 1,
            },
            {
                id: "116",
                rowName: "마",
                name: "4",
                isDisabled: false,
                state: 1,
            },
            {
                id: "117",
                rowName: "마",
                name: "5",
                isDisabled: false,
                state: 1,
            },
            {
                id: "118",
                rowName: "마",
                name: "6",
                isDisabled: false,
                state: 1,
            },
            {
                id: "119",
                rowName: "마",
                name: "7",
                isDisabled: false,
                state: 1,
            },
            {
                id: "120",
                rowName: "마",
                name: "8",
                isDisabled: false,
                state: 1,
            },
            {
                id: "121",
                rowName: "마",
                name: "9",
                isDisabled: false,
                state: 1,
            },
            {
                id: "122",
                rowName: "마",
                name: "10",
                isDisabled: false,
                state: 1,
            },
            {
                id: "123",
                rowName: "마",
                name: "11",
                isDisabled: false,
                state: 1,
            },
            {
                id: "124",
                rowName: "마",
                name: "12",
                isDisabled: false,
                state: 1,
            },
            {
                id: "125",
                rowName: "마",
                name: "13",
                isDisabled: false,
                state: 1,
            },
            {
                id: "126",
                rowName: "마",
                name: "14",
                isDisabled: false,
                state: 1,
            },
            {
                id: "127",
                rowName: "마",
                name: "15",
                isDisabled: false,
                state: 1,
            },
            {
                id: "128",
                rowName: "마",
                name: "16",
                isDisabled: false,
                state: 1,
            },
            {
                id: "129",
                rowName: "마",
                name: "17",
                isDisabled: false,
                state: 1,
            },
            {
                id: "130",
                rowName: "마",
                name: "18",
                isDisabled: false,
                state: 1,
            },
            {
                id: "131",
                rowName: "마",
                name: "19",
                isDisabled: false,
                state: 1,
            },
            {
                id: "132",
                rowName: "마",
                name: "20",
                isDisabled: false,
                state: 1,
            },
            {
                id: "133",
                rowName: "마",
                name: "21",
                isDisabled: false,
                state: 1,
            },
            {
                id: "134",
                rowName: "마",
                name: "22",
                isDisabled: false,
                state: 1,
            },
            {
                id: "135",
                rowName: "마",
                name: "23",
                isDisabled: false,
                state: 1,
            },
            {
                id: "136",
                rowName: "마",
                name: "24",
                isDisabled: false,
                state: 1,
            },
            {
                id: "137",
                rowName: "마",
                name: "25",
                isDisabled: false,
                state: 1,
            },
            {
                id: "138",
                rowName: "마",
                name: "26",
                isDisabled: false,
                state: 1,
            },
            {
                id: "139",
                rowName: "마",
                name: "27",
                isDisabled: false,
                state: 1,
            },
            {
                id: "140",
                rowName: "마",
                name: "28",
                isDisabled: false,
                state: 1,
            },
            {
                id: "141",
                rowName: "바",
                name: "1",
                isDisabled: false,
                state: 1,
            },
            {
                id: "142",
                rowName: "바",
                name: "2",
                isDisabled: false,
                state: 1,
            },
            {
                id: "143",
                rowName: "바",
                name: "3",
                isDisabled: false,
                state: 1,
            },
            {
                id: "144",
                rowName: "바",
                name: "4",
                isDisabled: false,
                state: 1,
            },
            {
                id: "145",
                rowName: "바",
                name: "5",
                isDisabled: false,
                state: 1,
            },
            {
                id: "146",
                rowName: "바",
                name: "6",
                isDisabled: false,
                state: 1,
            },
            {
                id: "147",
                rowName: "바",
                name: "7",
                isDisabled: false,
                state: 1,
            },
            {
                id: "148",
                rowName: "바",
                name: "8",
                isDisabled: false,
                state: 1,
            },
            {
                id: "149",
                rowName: "바",
                name: "9",
                isDisabled: false,
                state: 1,
            },
            {
                id: "150",
                rowName: "바",
                name: "10",
                isDisabled: false,
                state: 1,
            },
            {
                id: "151",
                rowName: "바",
                name: "11",
                isDisabled: false,
                state: 1,
            },
            {
                id: "152",
                rowName: "바",
                name: "12",
                isDisabled: false,
                state: 1,
            },
            {
                id: "153",
                rowName: "바",
                name: "13",
                isDisabled: false,
                state: 1,
            },
            {
                id: "154",
                rowName: "바",
                name: "14",
                isDisabled: false,
                state: 1,
            },
            {
                id: "155",
                rowName: "바",
                name: "15",
                isDisabled: false,
                state: 1,
            },
            {
                id: "156",
                rowName: "바",
                name: "16",
                isDisabled: false,
                state: 1,
            },
            {
                id: "157",
                rowName: "바",
                name: "17",
                isDisabled: false,
                state: 1,
            },
            {
                id: "158",
                rowName: "바",
                name: "18",
                isDisabled: false,
                state: 1,
            },
            {
                id: "159",
                rowName: "바",
                name: "19",
                isDisabled: false,
                state: 1,
            },
            {
                id: "160",
                rowName: "바",
                name: "20",
                isDisabled: false,
                state: 1,
            },
            {
                id: "161",
                rowName: "바",
                name: "21",
                isDisabled: false,
                state: 1,
            },
            {
                id: "162",
                rowName: "바",
                name: "22",
                isDisabled: false,
                state: 1,
            },
            {
                id: "163",
                rowName: "바",
                name: "23",
                isDisabled: false,
                state: 1,
            },
            {
                id: "164",
                rowName: "바",
                name: "24",
                isDisabled: false,
                state: 1,
            },
            {
                id: "165",
                rowName: "바",
                name: "25",
                isDisabled: false,
                state: 1,
            },
            {
                id: "166",
                rowName: "바",
                name: "26",
                isDisabled: false,
                state: 1,
            },
            {
                id: "167",
                rowName: "바",
                name: "27",
                isDisabled: false,
                state: 1,
            },
            {
                id: "168",
                rowName: "바",
                name: "28",
                isDisabled: false,
                state: 1,
            },
            {
                id: "169",
                rowName: "사",
                name: "1",
                isDisabled: false,
                state: 1,
            },
            {
                id: "170",
                rowName: "사",
                name: "2",
                isDisabled: false,
                state: 1,
            },
            {
                id: "171",
                rowName: "사",
                name: "3",
                isDisabled: false,
                state: 1,
            },
            {
                id: "172",
                rowName: "사",
                name: "4",
                isDisabled: false,
                state: 1,
            },
            {
                id: "173",
                rowName: "사",
                name: "5",
                isDisabled: false,
                state: 1,
            },
            {
                id: "174",
                rowName: "사",
                name: "6",
                isDisabled: false,
                state: 1,
            },
            {
                id: "175",
                rowName: "사",
                name: "7",
                isDisabled: false,
                state: 1,
            },
            {
                id: "176",
                rowName: "사",
                name: "8",
                isDisabled: false,
                state: 1,
            },
            {
                id: "177",
                rowName: "사",
                name: "9",
                isDisabled: false,
                state: 1,
            },
            {
                id: "178",
                rowName: "사",
                name: "10",
                isDisabled: false,
                state: 1,
            },
            {
                id: "179",
                rowName: "사",
                name: "11",
                isDisabled: false,
                state: 1,
            },
            {
                id: "180",
                rowName: "사",
                name: "12",
                isDisabled: false,
                state: 1,
            },
            {
                id: "181",
                rowName: "사",
                name: "13",
                isDisabled: false,
                state: 1,
            },
            {
                id: "182",
                rowName: "사",
                name: "14",
                isDisabled: false,
                state: 1,
            },
            {
                id: "183",
                rowName: "사",
                name: "15",
                isDisabled: false,
                state: 1,
            },
            {
                id: "184",
                rowName: "사",
                name: "16",
                isDisabled: false,
                state: 1,
            },
            {
                id: "185",
                rowName: "사",
                name: "17",
                isDisabled: false,
                state: 1,
            },
            {
                id: "186",
                rowName: "사",
                name: "18",
                isDisabled: false,
                state: 1,
            },
            {
                id: "187",
                rowName: "사",
                name: "19",
                isDisabled: false,
                state: 1,
            },
            {
                id: "188",
                rowName: "사",
                name: "20",
                isDisabled: false,
                state: 1,
            },
            {
                id: "189",
                rowName: "사",
                name: "21",
                isDisabled: false,
                state: 1,
            },
            {
                id: "190",
                rowName: "사",
                name: "22",
                isDisabled: false,
                state: 1,
            },
            {
                id: "191",
                rowName: "사",
                name: "23",
                isDisabled: false,
                state: 1,
            },
            {
                id: "192",
                rowName: "사",
                name: "24",
                isDisabled: false,
                state: 1,
            },
            {
                id: "193",
                rowName: "사",
                name: "25",
                isDisabled: false,
                state: 1,
            },
            {
                id: "194",
                rowName: "사",
                name: "26",
                isDisabled: false,
                state: 1,
            },
            {
                id: "195",
                rowName: "사",
                name: "27",
                isDisabled: false,
                state: 1,
            },
            {
                id: "196",
                rowName: "사",
                name: "28",
                isDisabled: false,
                state: 1,
            },
            {
                id: "197",
                rowName: "아",
                name: "1",
                isDisabled: false,
                state: 1,
            },
            {
                id: "198",
                rowName: "아",
                name: "2",
                isDisabled: false,
                state: 1,
            },
            {
                id: "199",
                rowName: "아",
                name: "3",
                isDisabled: false,
                state: 1,
            },
            {
                id: "200",
                rowName: "아",
                name: "4",
                isDisabled: false,
                state: 1,
            },
            {
                id: "201",
                rowName: "아",
                name: "5",
                isDisabled: false,
                state: 1,
            },
            {
                id: "202",
                rowName: "아",
                name: "6",
                isDisabled: false,
                state: 1,
            },
            {
                id: "203",
                rowName: "아",
                name: "7",
                isDisabled: false,
                state: 1,
            },
            {
                id: "204",
                rowName: "아",
                name: "8",
                isDisabled: false,
                state: 1,
            },
            {
                id: "205",
                rowName: "아",
                name: "9",
                isDisabled: true,
                state: 1,
            },
            {
                id: "206",
                rowName: "아",
                name: "10",
                isDisabled: true,
                state: 1,
            },
            {
                id: "207",
                rowName: "아",
                name: "11",
                isDisabled: true,
                state: 1,
            },
            {
                id: "208",
                rowName: "아",
                name: "12",
                isDisabled: true,
                state: 1,
            },
            {
                id: "209",
                rowName: "아",
                name: "13",
                isDisabled: true,
                state: 1,
            },
            {
                id: "210",
                rowName: "아",
                name: "14",
                isDisabled: true,
                state: 1,
            },
            {
                id: "211",
                rowName: "아",
                name: "15",
                isDisabled: true,
                state: 1,
            },
            {
                id: "212",
                rowName: "아",
                name: "16",
                isDisabled: true,
                state: 1,
            },
            {
                id: "213",
                rowName: "아",
                name: "17",
                isDisabled: true,
                state: 1,
            },
            {
                id: "214",
                rowName: "아",
                name: "18",
                isDisabled: true,
                state: 1,
            },
            {
                id: "215",
                rowName: "아",
                name: "19",
                isDisabled: true,
                state: 1,
            },
            {
                id: "216",
                rowName: "아",
                name: "20",
                isDisabled: true,
                state: 1,
            },
            {
                id: "217",
                rowName: "아",
                name: "21",
                isDisabled: false,
                state: 1,
            },
            {
                id: "218",
                rowName: "아",
                name: "22",
                isDisabled: false,
                state: 1,
            },
            {
                id: "219",
                rowName: "아",
                name: "23",
                isDisabled: false,
                state: 1,
            },
            {
                id: "220",
                rowName: "아",
                name: "24",
                isDisabled: false,
                state: 1,
            },
            {
                id: "221",
                rowName: "아",
                name: "25",
                isDisabled: false,
                state: 1,
            },
            {
                id: "222",
                rowName: "아",
                name: "26",
                isDisabled: false,
                state: 1,
            },
            {
                id: "223",
                rowName: "아",
                name: "27",
                isDisabled: false,
                state: 1,
            },
            {
                id: "224",
                rowName: "아",
                name: "28",
                isDisabled: false,
                state: 1,
            },
        ],
    },
];
